version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: etthos-postgres
    restart: always
    environment:
      POSTGRES_USER: ritesh
      POSTGRES_PASSWORD: ritesh25
      POSTGRES_DB: journal
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: etthos-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etthos.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data: