export interface EditorialBoardMemberData {
  id: string;
  name: string;
  title: string;
  role: "Editor-in-Chief" | "Associate Editor" | "Editorial Board Member" | "Reviewer";
  designation: string;
  department: string;
  institution: string;
  email: string;
  country: string;
  image: string | null;
  orcid?: string;
  expertise: string[];
  biography: string;
  displayOrder: number;
}

export const editorialBoard: EditorialBoardMemberData[] = [
  {
    id: "priyanka-verma",
    name: "Dr. Priyanka Verma",
    title: "Dr.",
    role: "Editor-in-Chief",
    designation: "Head of Institution & Associate Professor",
    department: "Amity Institute of Behavioural and Allied Sciences (AIBAS)",
    institution: "Amity University Haryana",
    email: "priyanka@ggn.amity.edu",
    country: "India",
    image: "/editorial-board/dr_priyanka.jpeg",
    expertise: ["Counselling Psychology", "Positive Psychology", "Psychometric Testing", "Organisational Behaviour", "Mental Health"],
    biography: "Dr. Priyanka Verma heads the Amity Institute of Behavioural and Allied Sciences (AIBAS) at Amity University Haryana. She established a Centre of Excellence for Psychometric Testing and holds three design patents in mental health innovation, including a VR Device for Mental Health Diagnostics.",
    displayOrder: 1,
  },
  {
    id: "pcs-devara",
    name: "Prof. (Dr.) Panuganti C.S. Devara",
    title: "Prof. (Dr.)",
    role: "Editorial Board Member",
    designation: "Director, Professor & Head — ACOAST, ACESH & ACAPC",
    department: "Centres of Excellence in Ocean-Atmospheric Science and Technology",
    institution: "Amity University Haryana, Gurugram",
    email: "pcsdevara@ggn.amity.edu",
    country: "India",
    image: "/editorial-board/prof-devara.jpeg",
    orcid: "0000-0002-2852-2017",
    expertise: ["Atmospheric Science", "Remote Sensing", "Climate & Weather", "Air Pollution Control", "Ocean Science"],
    biography: "Prof. Devara is an internationally recognised authority in atmospheric and environmental sciences with over four decades of sustained scientific contribution. A Fellow of the Royal Meteorological Society (UK) and Expert Reviewer for IPCC, he has authored over 585 research papers and supervised 12 doctoral scholars.",
    displayOrder: 2,
  },
  {
    id: "anu-gauba",
    name: "Dr. Anu Gauba",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Founder Principal, Department of Nursing",
    department: "Department of Nursing",
    institution: "GD Goenka University, Gurgaon, Haryana",
    email: "anu.gauba@gdgoenka.ac.in",
    country: "India",
    image: "/editorial-board/dr_annu.jpeg",
    expertise: ["Nursing Education", "Public Health", "Community Medicine", "Health Training & Policy", "Research"],
    biography: "Dr. Anu Gauba is a distinguished nursing educator and public health advocate with over two decades of experience. She holds the Chancellor's Gold Medal for Best PhD Thesis from the National Institute of Medical Sciences University, Jaipur, and has authored multiple academic publications including a monograph by Lambert Publications (UK).",
    displayOrder: 3,
  },
  {
    id: "luxita-sharma",
    name: "Dr. Luxita Sharma",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Associate Professor & Officiating Director, Amity Medical School; Head, Department of Dietetics and Applied Nutrition",
    department: "Department of Dietetics and Applied Nutrition",
    institution: "Amity University Haryana",
    email: "lsharma@ggn.amity.edu",
    country: "India",
    image: "/editorial-board/dr_luxita.jpeg",
    expertise: ["Clinical Nutrition", "Functional Foods", "Food Product Development", "Obesity & Metabolic Health", "Psycho-Nutrition"],
    biography: "Dr. Luxita Sharma is one of India's most prolific scholars in nutritional sciences with over two decades of experience. She has authored 18 books published by Wiley, CRC Press, and Springer, contributed over 118 research papers, and holds 10 patents. Her h-index of 9 reflects the sustained reach of her scholarly contributions.",
    displayOrder: 4,
  },
  {
    id: "pooja-rana",
    name: "Dr. Pooja Rana",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Professor & Head, PhD Programme",
    department: "Media & Communication",
    institution: "Amity University Haryana",
    email: "prana@ggn.amity.edu",
    country: "India",
    image: "/editorial-board/Dr_pooja_rana.jpeg",
    expertise: ["Media & Communication", "Digital Media Governance", "Journalism Studies", "Communication Policy", "Media Management"],
    biography: "Dr. Pooja Rana is a Professor and PhD Programme Head at Amity University Haryana with over two decades of distinguished experience. An award-winning scholar, she has authored several academic books on journalism and media studies widely referenced in higher education curricula across India.",
    displayOrder: 5,
  },
  {
    id: "vikas-sharma",
    name: "Dr. Vikas Sharma",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Associate Professor & Head, Department of Clinical Psychology",
    department: "Department of Clinical Psychology, Faculty of Behavioural Sciences",
    institution: "SGT University, Gurugram",
    email: "vikas.sharma@sgtuniversity.org",
    country: "India",
    image: null,
    expertise: ["Clinical Psychology", "Cognitive Behaviour Therapy", "Behavioural Medicine", "Sleep Research", "Psychological Assessment"],
    biography: "Dr. Vikas Sharma holds an M.Phil. in Clinical Psychology from IHBAS, New Delhi and a Doctorate from the University of Delhi. He has published over 50 research papers and is a member of the Indian Association of Clinical Psychologists (IACP) and the Indian Society of Sleep Research.",
    displayOrder: 6,
  },
  {
    id: "sanjay-jha",
    name: "Prof. Sanjay K. Jha",
    title: "Prof.",
    role: "Editorial Board Member",
    designation: "Director of Liberal Arts; Professor of Linguistics; Head, Amity Centre for Sanskrit and Indic Studies",
    department: "Liberal Arts & Linguistics",
    institution: "Amity University Haryana",
    email: "skjha@ggn.amity.edu",
    country: "India",
    image: "/editorial-board/dr_sanjay.jpeg",
    expertise: ["Applied Linguistics", "Sanskrit & Indic Studies", "Computational Linguistics", "Indian Knowledge Systems", "Machine Translation"],
    biography: "Prof. Sanjay K. Jha is a scholar of exceptional intellectual range — a linguist, polyglot, and institution builder. Proficient in 10 Indian and 5 foreign languages, he has published over 200 research papers, 9 books, and is Chief Editor of four international journals. He is the recipient of 23 prestigious awards.",
    displayOrder: 7,
  },
  {
    id: "neha-mishra",
    name: "Dr. Neha Mishra",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Assistant Professor of Law",
    department: "Department of Law",
    institution: "Amity University, Gurugram",
    email: "neha.mishra@amity.edu",
    country: "India",
    image: "/editorial-board/dr_neha.jpeg",
    expertise: ["Criminal Law", "Public Interest Litigation", "Judicial Activism", "Comparative Law", "Legal Scholarship"],
    biography: "Dr. Neha Mishra, LL.M., NET, Ph.D., is a legal scholar with over 12 years of professional experience, including 9 years of dedicated academic service. She specialises in Criminal Law with a focused research agenda encompassing public interest litigation and judicial activism.",
    displayOrder: 8,
  },
  {
    id: "akshay-ohlan",
    name: "Dr. Akshay Ohlan",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Assistant Professor of Psychology",
    department: "Department of Psychology",
    institution: "Amity University Haryana",
    email: "aohlan@ggn.amity.edu",
    country: "India",
    image: "/editorial-board/dr-akshay.jpeg",
    expertise: ["Positive Psychology", "Neuropsychology", "Suicide Prevention", "Mental Health", "Biopsychology"],
    biography: "Dr. Akshay Ohlan holds a PhD in Psychology from Guru Jambheshwar University and is a five-time UGC-NET qualified academician. His research spans positive psychology, neuropsychology, and suicide prevention. His publications appear in Scopus- and UGC-CARE-indexed journals.",
    displayOrder: 9,
  },
  {
    id: "alka-pandey",
    name: "Dr. Alka Pandey",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Assistant Professor, Department of Psychology",
    department: "Department of Psychology, School of Liberal Education",
    institution: "Galgotias University, Greater Noida",
    email: "alka.pandey@galgotiasuniversity.edu.in",
    country: "India",
    image: "/editorial-board/dr-alka-pandey.png",
    expertise: ["Child Guidance & Counselling", "Clinical Psychology", "Human Development", "Mental Health", "Life Skills Training"],
    biography: "Dr. Alka Pandey holds a PhD in Child Guidance and Family Counselling and a Post-Doctoral Fellowship from G.B. Pant University. She is a recipient of the ICAR-Junior Research Fellowship at All India 1st Rank, UGC-NET, and the Young Scientist Award. She has over 40 publications in Scopus-indexed journals.",
    displayOrder: 10,
  },
  {
    id: "ashwarya-raj-laxmi",
    name: "Dr. Ashwarya Raj Laxmi",
    title: "Dr.",
    role: "Editorial Board Member",
    designation: "Research Medical Officer & Ayurvedic Physician; MS Scholar, Prasuti Tantra evum Stree Roga",
    department: "Ayurvedic Medicine & Integrative Women's Healthcare",
    institution: "Independent Practitioner",
    email: "ashwarya.rajlaxmi@gmail.com",
    country: "India",
    image: "/editorial-board/dr_aishwarya.jpeg",
    expertise: ["Ayurvedic Medicine", "Women's Health", "Clinical Obstetrics", "Integrative Healthcare", "Nutritional Counselling"],
    biography: "Dr. Ashwarya Raj Laxmi is a qualified Ayurvedic physician and clinical researcher specialising in Prasuti Tantra evum Stree Roga (Obstetrics & Gynaecology). Her practice integrates classical Shastraic knowledge with contemporary clinical protocols for women's healthcare.",
    displayOrder: 11,
  },
];
